server:
  port: 8509
  servlet:
    context-path: /price_engine
  ssl:
    enabled: false
#  compression:
#    enabled: true
#    mime-types: application/json

spring:
  application:
    name: price-engine
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/enginedb?currentSchema=engineuser
    username: engineuser
    password: engineuser
    hikari:
      connection-init-sql: SELECT 1
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
#        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        show_sql: true
        format_sql: true
  jackson: # to get underscores for the json response
    property-naming-strategy: SNAKE_CASE
#    mapper:
#      default-view-inclusion: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    migrate: true
    repair: false
#    baseline-on-migrate: true
    table: schema_flyway_price_engine
    out-of-order: true
    sql-migration-prefix: ""
